(Dialog masterstudentcreo
    (Components
        (SubLayout LayoutParameters)
    )
    (Resources
        (.Label "Parametric Model")
        (.ResourceHints "Version:Creo4")
        (.Resizeable False)
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1)
                (Cols 0)
                LayoutParameters
            )
        )
    )
)
(Layout LayoutParameters
    (Components
        (Label LabelBaseLength)
        (InputPanel InputPanelBaseLength)
        (Label LabelVerticalLength)
        (InputPanel InputPanelVerticalLength)
        (Label LabelExtrusionLength)
        (InputPanel InputPanelExtrusionLength)
        (Label LabelThickness)
        (InputPanel InputPanelThickness)
        (Label LabelDstFrstRef)
        (InputPanel InputPanelDstFrstRef)
        (Label LabelDstFromScndRef)
        (InputPanel InputPanelDstScndRef)
        (Label LabelDiameter)
        (InputPanel InputPanelDimeter)
        (Separator Separator1)
        (PushButton PushButtonCreate)
    )
    (Resources
        (LabelBaseLength.Label "Base Length")
        (LabelBaseLength.Columns 10)
        (LabelBaseLength.TopOffset 3)
        (LabelBaseLength.BottomOffset 0)
        (LabelBaseLength.LeftOffset 4)
        (LabelBaseLength.RightOffset 0)
        (LabelBaseLength.Alignment 0)
        (InputPanelBaseLength.Columns 10)
        (InputPanelBaseLength.TopOffset 3)
        (InputPanelBaseLength.BottomOffset 0)
        (InputPanelBaseLength.LeftOffset 0)
        (InputPanelBaseLength.RightOffset 3)
        (InputPanelBaseLength.InputType 3)
        (LabelVerticalLength.Label "Vertical Length")
        (LabelVerticalLength.Columns 10)
        (LabelVerticalLength.Alignment 0)
        (LabelVerticalLength.TopOffset 0)
        (LabelVerticalLength.BottomOffset 0)
        (LabelVerticalLength.LeftOffset 4)
        (LabelVerticalLength.RightOffset 0)
        (InputPanelVerticalLength.TopOffset 0)
        (InputPanelVerticalLength.BottomOffset 0)
        (InputPanelVerticalLength.LeftOffset 0)
        (InputPanelVerticalLength.RightOffset 3)
        (InputPanelVerticalLength.InputType 3)
        (LabelExtrusionLength.Label "Extrusion Length")
        (LabelExtrusionLength.Columns 10)
        (LabelExtrusionLength.Alignment 0)
        (LabelExtrusionLength.TopOffset 0)
        (LabelExtrusionLength.BottomOffset 0)
        (LabelExtrusionLength.LeftOffset 4)
        (LabelExtrusionLength.RightOffset 0)
        (InputPanelExtrusionLength.TopOffset 0)
        (InputPanelExtrusionLength.BottomOffset 0)
        (InputPanelExtrusionLength.LeftOffset 0)
        (InputPanelExtrusionLength.RightOffset 3)
        (InputPanelExtrusionLength.InputType 3)
        (LabelThickness.Label "Thickness")
        (LabelThickness.Columns 10)
        (LabelThickness.Alignment 0)
        (LabelThickness.TopOffset 0)
        (LabelThickness.BottomOffset 0)
        (LabelThickness.LeftOffset 4)
        (LabelThickness.RightOffset 0)
        (InputPanelThickness.TopOffset 0)
        (InputPanelThickness.BottomOffset 0)
        (InputPanelThickness.LeftOffset 0)
        (InputPanelThickness.RightOffset 3)
        (InputPanelThickness.InputType 3)
        (LabelDstFrstRef.Label "Dist. from frst. ref.")
        (LabelDstFrstRef.Columns 10)
        (LabelDstFrstRef.Alignment 0)
        (LabelDstFrstRef.TopOffset 0)
        (LabelDstFrstRef.BottomOffset 0)
        (LabelDstFrstRef.LeftOffset 4)
        (LabelDstFrstRef.RightOffset 0)
        (InputPanelDstFrstRef.TopOffset 0)
        (InputPanelDstFrstRef.BottomOffset 0)
        (InputPanelDstFrstRef.LeftOffset 0)
        (InputPanelDstFrstRef.RightOffset 3)
        (InputPanelDstFrstRef.InputType 3)
        (LabelDstFromScndRef.Label "Dist. from sec. ref.")
        (LabelDstFromScndRef.Columns 10)
        (LabelDstFromScndRef.Alignment 0)
        (LabelDstFromScndRef.TopOffset 0)
        (LabelDstFromScndRef.BottomOffset 0)
        (LabelDstFromScndRef.LeftOffset 4)
        (LabelDstFromScndRef.RightOffset 0)
        (InputPanelDstScndRef.TopOffset 0)
        (InputPanelDstScndRef.BottomOffset 0)
        (InputPanelDstScndRef.LeftOffset 0)
        (InputPanelDstScndRef.RightOffset 3)
        (InputPanelDstScndRef.InputType 3)
        (LabelDiameter.Label "Diameter")
        (LabelDiameter.Columns 10)
        (LabelDiameter.Alignment 0)
        (LabelDiameter.TopOffset 0)
        (LabelDiameter.BottomOffset 0)
        (LabelDiameter.LeftOffset 4)
        (LabelDiameter.RightOffset 0)
        (InputPanelDimeter.TopOffset 0)
        (InputPanelDimeter.BottomOffset 3)
        (InputPanelDimeter.LeftOffset 0)
        (InputPanelDimeter.RightOffset 3)
        (InputPanelDimeter.InputType 3)
        (PushButtonCreate.Label "Create")
        (PushButtonCreate.AttachRight True)
        (PushButtonCreate.TopOffset 0)
        (PushButtonCreate.BottomOffset 0)
        (PushButtonCreate.LeftOffset 0)
        (PushButtonCreate.RightOffset 3)
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1 0 0 0 0 0 0 0 0)
                (Cols 1 0)
                LabelBaseLength InputPanelBaseLength LabelVerticalLength InputPanelVerticalLength LabelExtrusionLength InputPanelExtrusionLength LabelThickness InputPanelThickness LabelDstFrstRef InputPanelDstFrstRef LabelDstFromScndRef InputPanelDstScndRef LabelDiameter InputPanelDimeter
                (Size 1 2)
                Separator1
                (Pos 9 2)
                PushButtonCreate
            )
        )
    )
)
